- hosts: all
  tasks:

  - name: Register and auto-subscribe to available content
    redhat_subscription:
      state: present
      username: barisaku
      password: 
      auto_attach: true
      force_register: true
    register: r
    until: r is succeeded
